spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Star
    username: root
    password: GYh031125
  session:
    timeout: 86400  #设置session超时时间 一天86400秒
    store-type: redis
  redis:
    port: 6379
    host: localhost
    database: 1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值


server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

